project: 
  type: website
  output-dir: docs
  render:
    - "*.*"
    - "!nasa-tutorials/*.ipynb"

execute:
  freeze: auto
  
website:
  page-navigation: true  
  title: "2023 ITCOocean Hack2week"
  favicon: images/incois-icon.png
  site-url: https://Hackweek-ITCOocean.github.io/2023-Hackbook
  repo-url: https://github.com/Hackweek-ITCOocean/2023-Hackbook
  repo-actions: [edit, issue, source]
  
  page-footer: <img src="/images/incois.png" alt="INCOIS logo" style="width:150px"><br />ITCOocean Hack2week (2023)
 
  sidebar:
    logo: images/incois-logos.png
    pinned: true
    align: center
    
    style: "docked"
    collapse-level: 1
    toc-expand: false
    contents:
      - section: "Welcome"
        href: index.md
        contents:
          - overview.md
          - team.md
          - schedule.md
          - setup.md
          - support.md
          - hackweek-links.md
          - coc.md
      - section: "Tutorials"
        contents:
          - section: "01 Monday"
            contents:
              - text: Welcome
                href: content/01-welcome.md
              - text: GitHub 1
                href: content/01-github.md
              - text: Geoscience cloud tools
                href: content/01-intro-to-cloud-geoscience.qmd
              - text: Jupyter hubs
                href: content/01-intro-to-jupyterhub.qmd
          - section: "01 Tuesday"
            contents:
              - text: RStudio
                href: content/02-rstudio.qmd
              - text: GitHub 2
                href: content/02-github-2.md
              - text: Quarto
                href: content/02-quarto.qmd
          - section: "01 Wednesday"
            contents:
              - text: Programming with AI
                href: content/03-ai.md
              - text: Git
                href: content/03-git-rstudio.md
              - text: Loading data in R
                href: r-tutorials/03-r-read-in-data.qmd
          - section: "01 Thursday"
            contents:
              - text: Lab Setup
                href: r-tutorials/Lab-setup.qmd
              - text: Plotting with ggplot2
                href: r-tutorials/04-r-ggplot2.qmd
          - section: "01 Friday"
            contents:
              - text: Maps!
                href: r-tutorials/05-r-geospatial.qmd
          - section: "02 Monday"
            contents:
              - text: SDM 1
                href: r-tutorials/SDM-lab1.qmd
      - section: "Projects"
        contents:
          - projects/index.md
          - projects/hackathon-projects.md
      - section: "Further Resources"
        contents:
          - content/XX-r-and-python-resources.md
          - content/XX-further-resources.md
      - section: "Python Tutorials"
        contents:
          - section: "Data Access"
            contents:
              - python-notebooks/00_NASA_Earthdata_Authentication.ipynb
              - python-notebooks/01_earthaccess_Downloader.ipynb
              - python-notebooks/01_ERA5_S3_Downloader.ipynb
              - python-notebooks/01_ERDDAP_Downloader.ipynb
              - python-notebooks/01_MOTU_Downloader.ipynb
          - section: "Using Data"
            contents:
              - python-notebooks/02_Using_Data.ipynb
              - python-notebooks/02_Graphing_Data.ipynb
              - python-notebooks/02_Zarr_Access_netCDF.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb
              - python-notebooks/02_Xarray_hvplot.ipynb              
          - section: "Machine Learning"
            contents:
          - section: "Applications"
            contents:
          - section: "IO Zarr Database"
            contents:
              - python-notebooks/04_Combining_Data.ipynb
              - python-notebooks/04_Appending_Data.ipynb
      - text: <img width=100px>
      - text: <img src="/images/ecsn.png" width=100px>
        href: https://iioe-2.incois.gov.in/ecsn/index.html
      - text: <img src="/images/ocean-decade.png" width=150px>
        href: https://oceandecade.org/
      - text: <img src="/images/dcc-ior.png" width=150px>
        href: https://incois.gov.in/dcc-ior/index.jsp
      - text: <img src="/images/ecop.png" width=150px>
        href: https://www.ecopdecade.org/
      - text: DECCaD-IO
        href: https://oceandecade.org/actions/devising-early-career-capacity-development-indocn-deccad-io/
      - text: <img src="/images/ohw.png" width=150px>
        href: https://www.oceanhackweek.org/

  navbar:
    background: primary
    search: true
    right: 
      - icon: server
        href: https://itcoocean.2i2c.cloud/
        text: "JupyterHub"
      - icon: wechat
        href: https://github.com/orgs/Hackweek-ITCOocean/discussions
        text: "Discussions"
      - icon: slack
        href: https://app.slack.com/client/T05PV2USY56/C05P7QP47UL
        text: "Slack"
      - icon: globe
        href: https://github.com/Hackweek-ITCOocean
        text: "GH org"


format:
  html:
    theme:
      light: cosmo
      dark: [cosmo, theme-dark.scss]
    code-background: true
    code-copy: true
    css: styles.css
    toc: true
    toc-depth: 2
    include-before-body: translate.html

filters:
  - include-files.lua
  - quarto
